################################################################################
# Automatically-generated file. Do not edit!
################################################################################

OBJ_SRCS := 
S_SRCS := 
ASM_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
EXECUTABLES := 
OBJS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
HAL_Driver/Src/Legacy \
HAL_Driver/Src \
Middlewares/ST/STM32_USB_Device_Library/Class/AUDIO/Src \
Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src \
Middlewares/ST/STM32_USB_Device_Library/Class/CustomHID/Src \
Middlewares/ST/STM32_USB_Device_Library/Class/DFU/Src \
Middlewares/ST/STM32_USB_Device_Library/Class/HID/Src \
Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Src \
Middlewares/ST/STM32_USB_Device_Library/Class/Template/Src \
Middlewares/ST/STM32_USB_Device_Library/Core/Src \
Middlewares/ST/STM32_USB_Host_Library/Class/AUDIO/Src \
Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Src \
Middlewares/ST/STM32_USB_Host_Library/Class/HID/Src \
Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Src \
Middlewares/ST/STM32_USB_Host_Library/Class/MTP/Src \
Middlewares/ST/STM32_USB_Host_Library/Class/Template/Src \
Middlewares/ST/STM32_USB_Host_Library/Core/Src \
Middlewares/ST/STemWin/Config \
Middlewares/ST/STemWin/OS \
Middlewares/ST/STemWin/Simulation \
Middlewares/Third_Party/FatFs/doc/res \
Middlewares/Third_Party/FatFs/src \
Middlewares/Third_Party/FatFs/src/drivers \
Middlewares/Third_Party/FatFs/src/option \
Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS \
Middlewares/Third_Party/FreeRTOS/Source \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F \
Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang \
Middlewares/Third_Party/LibJPEG \
Middlewares/Third_Party/LibJPEG/source \
Middlewares/Third_Party/LwIP/doc \
Middlewares/Third_Party/LwIP/src/api \
Middlewares/Third_Party/LwIP/src/apps/httpd \
Middlewares/Third_Party/LwIP/src/apps/httpd/makefsdata \
Middlewares/Third_Party/LwIP/src/apps/lwiperf \
Middlewares/Third_Party/LwIP/src/apps/mdns \
Middlewares/Third_Party/LwIP/src/apps/mqtt \
Middlewares/Third_Party/LwIP/src/apps/netbiosns \
Middlewares/Third_Party/LwIP/src/apps/snmp \
Middlewares/Third_Party/LwIP/src/apps/sntp \
Middlewares/Third_Party/LwIP/src/apps/tftp \
Middlewares/Third_Party/LwIP/src/core \
Middlewares/Third_Party/LwIP/src/core/ipv4 \
Middlewares/Third_Party/LwIP/src/core/ipv6 \
Middlewares/Third_Party/LwIP/src/netif \
Middlewares/Third_Party/LwIP/src/netif/ppp \
Middlewares/Third_Party/LwIP/src/netif/ppp/polarssl \
Middlewares/Third_Party/LwIP/system/OS \
Middlewares/Third_Party/LwIP/test/fuzz \
Middlewares/Third_Party/LwIP/test/unit/core \
Middlewares/Third_Party/LwIP/test/unit/dhcp \
Middlewares/Third_Party/LwIP/test/unit/etharp \
Middlewares/Third_Party/LwIP/test/unit/ip4 \
Middlewares/Third_Party/LwIP/test/unit \
Middlewares/Third_Party/LwIP/test/unit/mdns \
Middlewares/Third_Party/LwIP/test/unit/tcp \
Middlewares/Third_Party/LwIP/test/unit/udp \
Utilities/Components/cs43l22 \
Utilities/Components/exc7200 \
Utilities/Components/ft6x06 \
Utilities/Components/ili9325 \
Utilities/Components/ili9341 \
Utilities/Components/l3gd20 \
Utilities/Components/lis302dl \
Utilities/Components/lis3dsh \
Utilities/Components/ls016b8uy \
Utilities/Components/lsm303dlhc \
Utilities/Components/mfxstm32l152 \
Utilities/Components/otm8009a \
Utilities/Components/ov2640 \
Utilities/Components/s5k5cag \
Utilities/Components/st7735 \
Utilities/Components/st7789h2 \
Utilities/Components/stmpe1600 \
Utilities/Components/stmpe811 \
Utilities/Components/ts3510 \
Utilities/Components/wm8994 \
Utilities/STM32F4-Discovery \
src \

